name: audio_service_win
description: "Platform interface allows you to use `audio_service` on Windows."
version: 0.0.1
homepage: https://github.com/HemantKArya/audio_service_win

repository:
  type: git
  url: https://github.com/HemantKArya/audio_service_win
environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  audio_service_platform_interface: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    implements: audio_service_platform_interface
    platforms:
      windows:
        dartPluginClass: AudioServiceWin
        fileName: audio_service_win.dart
        pluginClass: AudioServiceWinPluginCApi
